spring.application.name=Lambda_Snapstart_APIGateway

spring.main.web-application-type=servlet
logging.level.root=INFO
# SnapStart optimizations
spring.main.lazy-initialization=true
spring.jmx.enabled=false

